### ISSUE TITLE
Resolving the Issue of Retrieving OHLCV Data

### ISSUE THREAD

**Issue by Ahmed-Z-D** [s0v1x/StocksMA#10]
In accordance with the details provided in issue #9, it has been reported that the `get_price_data()` function is presently incapable of retrieving the data it was designed to obtain. Included below is a code snippet that is causing the error, along with the corresponding error message:

```python
import StocksMA as stm

stm.get_price_data('maroc telecom', start_date='2020-11-14', end_date='2022-02-14')
```

```python

    138     return pd.concat(dataframes, sort=True)
    139 else:
--> 140     return get_data_stock(tickers, start_date, end_date)
  # ...
     72 def get_data_stock(company: str, start_date: str, end_date: T_ed) -> pd.DataFrame:
     73     """Get historical OHLCV data for a given symbol
     74     Args:
     75         company (str): Company name or ticker symbol(e.g. 'maroc telecom', 'MNG')
   (...)
     80         pd.DataFrame: Dataframe of historical OHLCV data
     81     """
---> 82     name, isin = get_isin(company)
 # ...
     45 request_data = utils.get_request(url)
     46 # r.encoding='utf-8-sig'
---> 47 result = json.loads(request_data.content)["result"]
  # ...
    353     obj, end = self.scan_once(s, idx)
    354 except StopIteration as err:
--> 355     raise JSONDecodeError("Expecting value", s, err.value) from None
    356 return obj, end

JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
Following a thorough investigation, it has been ascertained that the root cause of the issue is connected to `Leboursier's` alteration of its domain name and the resultant modification of certain endpoints. This explains why the `get_isin()` function - which is used indirectly by `get_price_data()` to retrieve the ISIN of one or more companies - is unable to retrieve the ISIN due to the endpoint responding with an HTTP 301 status code, which redirects the Get request to a different page that does not contain the desired data. As a result, the function receives HTML content instead of the expected JSON response, which leads to the parsing error displayed in the error message.

Given the previous statement, the question posed is whether modifying both the domain name and the path from `https://www.leboursier.ma/api?{Query string}` to `https://medias24.com/content/api?{Query string}` would effectively resolve the issues that are currently hindering the functionality of `get_isin()`, `get_data_stock()`, and `get_price_data()`?

In response to this, the answer is affirmative, but it is crucial to note that not all functions in the source code will be impacted by this modification. To help clarify which functions are still operating under the previous endpoints and which ones are not, please refer to the table below for a concise summary:

|Function| Previous endpoint| Current endpoint|
| :-------------- | ------------- | -------------: |
| get_isin()  |:x:|:x:|
| get_data_stock() |:x:| :heavy_check_mark: |
| get_session_info() |:x:| :heavy_check_mark: |
| get_data_intraday() |:x:| :heavy_check_mark: |
| get_ask_bid() |:x:| :heavy_check_mark: |
| get_best_performers() |:heavy_check_mark:| - |
| get_worst_performers() |:heavy_check_mark:|  - |

The table presents a concern regarding how to address the issue with` get_isin().` Since a company's ISIN is a static piece of information, it is unnecessary to make costly GET requests to the server each time `get_isin()` is invoked to retrieve that information. Consequently, the solution is to store all ISINs in either a separate dictionary or, ideally, to include them in the `COMPANIES `constant.

To conclude, I would be delighted to submit a pull request that integrates this solution. Moreover, if I have not done so already, I hope that the explanation provided here may be sufficient to help users resolve the issue. 

Speaking of pull requests, @s0v1x, are you still invested in this project? I would be delighted to contribute a set of pull requests with the goal of enhancing performance and increasing the unit test coverage to cover a minimum of 80% of the code base.

P.S. As indicated in the project's [README.md](https://github.com/s0v1x/StocksMA#readme) file, the project leverages various websites to obtain the financial data it offers, and admittedly, I have exclusively focused on `Leboursier`. Consequently, I cannot currently confirm or deny whether the other sources of data continue to function as intended. Additionally, I want to clarify that I have tested only the endpoints used by the functions to retrieve data from `Leboursier`, and not the functions themselves, except for `get_isin()`, `get_data_stock()`, and `get_price_data()`.

**Comment by s0v1x** [comment]
Hello @Ahmed-Z-D,
Thank you for your detailed analysis of the issue with the ``get_price_data()`` function and your proposed solution. Your insight on the root cause of the problem and its impact on other functions is truly informative!
I did attempt to fix it, but unfortunately, I did not have sufficient time to fully investigate and implement a proper solution. I appreciate your efforts in bringing attention to the issue and providing a detailed analysis of the root cause and potential solutions.
Your suggestion to modify the endpoint ``get_data_stock()``, `` get_session_info()``,  ``get_data_intraday()``, and ``get_ask_bid()`` is definitely a step in the right direction. However, as you mentioned, ``get_isin()`` still requires further attention. Storing all ISINs in a separate dictionary or in the COMPANIES constant is an excellent idea, and it will certainly reduce the need for costly GET requests to the server. It would be fantastic if you could submit a pull request with this solution.

I truly appreciate your offer to contribute a PR to enhance performance and increase unit test coverage. It is critical to thoroughly test all functions to ensure that the package functions correctly. Please feel free to create an issue about that to discuss your ideas.

**Comment by Ahmed-Z-D** [comment]
That sounds great! Without delay, I will proceed to submit a pull request in the coming days.
